FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

COPY ./MiniTwitAPI .

RUN dotnet restore ./MiniTwitAPI.sln

RUN dotnet publish MiniTwit.API -o ./out

FROM mcr.microsoft.com/dotnet/aspnet:5.0

EXPOSE 80

COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "MiniTwit.API.dll"]