FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

COPY ./MiniTwitAPI .

RUN dotnet restore ./MiniTwitAPI.sln

RUN dotnet publish MiniTwit.Blazor -o ./out

FROM mcr.microsoft.com/dotnet/aspnet:5.0

COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "MiniTwit.Blazor.dll"]