Vagrant.configure('2') do |config|

config.vm.define "dbserver" do |config|
	config.vm.provider :digital_ocean do |provider, override|
override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	config.vm.network "forwarded_port", guest: 3306, host: 3306
        override.nfs.functional = false
        override.vm.allowed_synced_folder_types = :rsync
        provider.image = 'ubuntu-18-04-x64'
        provider.region = 'AMS3'
        provider.size = 's-1vcpu-1gb'
        provider.backups_enabled = false
        provider.private_networking = false
        provider.ipv6 = false
        provider.monitoring = false
	end

	config.vm.provision "shell", privileged: false, inline: <<-SHELL
	echo "Installing git"
	sudo apt-get update
	sudo apt-get install git
	echo "Cloning Minitwit"
	git clone -b development https://github.com/SanderBuK/DevOpsMinitwit
	echo "Curling sqlite to mysql conversion"
	curl -F files[]=@DevOpsMinitwit/MiniTwitAPI/MiniTwit.API/MiniTwit.db 'https://www.rebasedata.com/api/v1/convert?outputFormat=mysql&errorResponse=zip' -o output.zip
	echo "Installing unzip"
	sudo apt install unzip
	echo "Unzipping database"
	unzip output.zip
	echo "Installing MySQL"
	sudo apt-get install -y mysql-client-core-5.7
	sudo apt-get install -y mysql-server
	sed -i -e 's/127.0.0.1/0.0.0.0/g' ../etc/mysql/mysql.conf.d/mysqld.cnf
	sudo systemctl restart mysql
	sudo iptables -A INPUT -p tcp --destination-port 3306 -j ACCEPT
	iptables-save
	mysql -u root -e "create database MiniTwit";	
	mysql -u root MiniTwit < data.sql 

	echo "Altering tables"
	mysql -u root -e "ALTER TABLE MiniTwit.user MODIFY user_id int NOT NULL auto_increment PRIMARY KEY;"
	mysql -u root -e "ALTER TABLE MiniTwit.user MODIFY username varchar(50);"
	mysql -u root -e "ALTER TABLE MiniTwit.user MODIFY email varchar(50);"

	mysql -u root -e "ALTER TABLE MiniTwit.follower MODIFY who_id int;"
	mysql -u root -e "ALTER TABLE MiniTwit.follower MODIFY whom_id int;"
	mysql -u root -e "ALTER TABLE MiniTwit.follower ADD PRIMARY KEY(who_id, whom_id);"

	mysql -u root -e "ALTER TABLE MiniTwit.message MODIFY message_id int NOT NULL auto_increment PRIMARY KEY;"
	mysql -u root -e "ALTER TABLE MiniTwit.message MODIFY author_id int NOT NULL;"
	mysql -u root -e "ALTER TABLE MiniTwit.message MODIFY text TEXT;"
	mysql -u root -e "ALTER TABLE MiniTwit.message MODIFY pub_date bigint;"
	mysql -u root -e "ALTER TABLE MiniTwit.message MODIFY flagged int;"

	mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
	mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'admin' WITH GRANT OPTION;"
	SHELL
  end
end
